This is our first project /Embbeding images video
davidauza-engineer/PROJECT-EMBEDDING-IMAGES-AND-VIDEO pull request #1
Opened 2019-07-19 22:13 UTC by eduardoreisalvarenga

Please let us know what you think

2019-07-20 21:27 UTC, Ispirett commented
#reviewing

2019-07-20 21:38 UTC, Ispirett requested changes
Hey, folks exceptional work with this project you are doing a fantastic job :1st_place_medal:  .There are just a few changes that Mircoverse requires before this project can be completed.

### Sidebar Recommended videos
- [x] **Optional** instead of img tag with images  you can use `<iframe>` with videos
- [x] **Optional** It is better to use classes instead of ids. Ids are mostly used in javascript and id's are unique so limits you from reusing them.
- [x] Please put more information in you read me about and your name.
### html errors
There are a lot of HTML errors on this page use this tool and please correct them https://validator.w3.org/

When finished with these changes please submit for another code review you can use this same pull request link.

2019-07-20 21:38 UTC, Ispirett commented on index.html
> +                <div class="search-container">
User a button here instead of input.

2019-07-22 20:52 UTC, davidauza-engineer commented on index.html
> +                <div class="search-container">
Done :)

2019-07-23 07:39 UTC, Oghenebrume50 commented
Great work team everything works perfectly, submit a project completion form and move to the next project, kudos for working with Github flow. Awesome.

2019-07-23 16:22 UTC, davidauza-engineer commented
Thank you very much guys!

2019-07-23 16:23 UTC, merged